project_id = "fcdwldktezqpzzfexqoj"

[functions.stripe-connect-onboarding]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.send-enquiry-email]
verify_jwt = false

[functions.verify-stripe-status]
verify_jwt = false

[functions.checkout-session]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = false

[functions.get-customer-invoices]
verify_jwt = false

[functions.update-customer-subscription]
verify_jwt = false
